/*1번*/
SELECT
	STUDENT_NAME "학생 이름",
	STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-----------------------------------------------
/*2번*/
SELECT
	STUDENT_NAME,
	STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-----------------------------------------------
/*3번*/
SELECT
	STUDENT_NAME "학생이름",
	STUDENT_NO "학번",
	STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '경기도%'
	AND STUDENT_NO LIKE '9%'; 

-----------------------------------------------
/*4번*/
SELECT
	PROFESSOR_NAME,
	PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN ASC;

-----------------------------------------------
/*5번*/
SELECT
	STUDENT_NO ,
	TO_CHAR(ROUND(AVG(POINT),1),'FM9.00') "학점"
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
	AND TERM_NO = '200402'
GROUP BY STUDENT_NO
ORDER BY 학점 DESC;

-----------------------------------------------
/*6번*/
SELECT
	STUDENT_NO,
	STUDENT_NAME,
	DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

-----------------------------------------------
/*7번*/
SELECT
	CLASS_NAME,
	DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO;

-----------------------------------------------
/*8번*/
SELECT
	CLASS_NAME,
	PROFESSOR_NAME
FROM TB_CLASS C, TB_PROFESSOR P
WHERE C.DEPARTMENT_NO = P.DEPARTMENT_NO
ORDER BY CLASS_TYPE;

-----------------------------------------------
/*9번*/
SELECT
	CLASS_NAME,
	PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY CLASS_NAME;


------------------------------------------------
/*10번*/
SELECT
	STUDENT_NO "학번",
	STUDENT_NAME "학생 이름",
	ROUND(AVG(POINT), 1) AS "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY "학번" ASC;

------------------------------------------------
/*11번*/
SELECT
	DEPARTMENT_NAME "학과이름",
	STUDENT_NAME "학생이름",
	PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING(DEPATNENT_NO)
WHERE STUDENT_NO = 'A313047';

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR 
WHERE PROFESSOR_NO = 'P034';